// WiseTransact — PDF report generator (PRD §6.9)
// Uses jsPDF (loaded via CDN in index.html).
// Generates a year-end report with: metadata, summary, category & purpose breakdown,
// monthly trend, account-level breakdown, full transaction register, anomalies.

const generateReportPdf = ({ transactions, periodLabel, userName = "Rishi Raj Sahu", accounts = [] }) => {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const MARGIN = 40;
  let y = MARGIN;

  // Brand colors (rgb)
  const C = {
    emerald:   [4, 120, 87],
    emeraldBg: [236, 253, 245],
    rose:      [244, 63, 94],
    gray900:   [17, 24, 39],
    gray700:   [55, 65, 81],
    gray500:   [107, 114, 128],
    gray400:   [156, 163, 175],
    gray200:   [229, 231, 235],
    gray100:   [243, 244, 246],
    gray50:    [249, 250, 251],
    white:     [255, 255, 255],
  };

  const setFill = (rgb) => doc.setFillColor(rgb[0], rgb[1], rgb[2]);
  const setText = (rgb) => doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  const setStroke = (rgb) => doc.setDrawColor(rgb[0], rgb[1], rgb[2]);

  const ensureSpace = (h) => {
    if (y + h > PAGE_H - MARGIN) {
      addFooter();
      doc.addPage();
      y = MARGIN;
    }
  };

  const addFooter = () => {
    setText(C.gray400);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    const txt = "Generated by WiseTransact based on user-entered data. Verify all entries with original bank statements and consult a qualified Chartered Accountant before tax filing.";
    const lines = doc.splitTextToSize(txt, PAGE_W - MARGIN * 2);
    doc.text(lines, MARGIN, PAGE_H - 30);
    doc.text(`Page ${doc.internal.getNumberOfPages()}`, PAGE_W - MARGIN, PAGE_H - 30, { align: "right" });
  };

  const h2 = (label) => {
    ensureSpace(36);
    setText(C.gray900);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(label, MARGIN, y);
    y += 6;
    setStroke(C.emerald);
    doc.setLineWidth(1.5);
    doc.line(MARGIN, y, MARGIN + 40, y);
    y += 18;
  };

  const body = (text, size = 9.5, weight = "normal", color = C.gray700) => {
    setText(color);
    doc.setFont("helvetica", weight);
    doc.setFontSize(size);
    doc.text(text, MARGIN, y);
    y += size + 4;
  };

  const inr = (n) => "Rs. " + Math.abs(n).toLocaleString("en-IN", { maximumFractionDigits: 0 });

  // ----------- 1. HEADER -----------
  // Logo dot
  setFill(C.emerald);
  doc.circle(MARGIN + 12, y + 8, 12, "F");
  setText(C.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("W", MARGIN + 9, y + 12);

  setText(C.gray900);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("WiseTransact", MARGIN + 34, y + 14);

  setText(C.gray500);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Year-end transaction report", MARGIN + 34, y + 28);

  setText(C.gray500);
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}`, PAGE_W - MARGIN, y + 14, { align: "right" });
  doc.text(`Period: ${periodLabel}`, PAGE_W - MARGIN, y + 28, { align: "right" });

  y += 56;
  setStroke(C.gray200);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 24;

  // ----------- 2. METADATA -----------
  h2("Report Details");
  body(`Prepared for: ${userName}`, 10, "normal", C.gray900);
  body(`Accounts covered: ${accounts.length ? accounts.map(a => a.name).join(", ") : "All accounts"}`);
  body(`Total transactions: ${transactions.length}`);
  y += 8;

  // ----------- 3. SUMMARY -----------
  const totals = totalsFor(transactions);
  h2("Summary");

  const summaryCards = [
    { label: "Income",   value: inr(totals.income),  color: C.emerald,   bg: C.emeraldBg },
    { label: "Expenses", value: inr(totals.expense), color: C.rose,      bg: [255, 228, 230] },
    { label: "Net",      value: (totals.net < 0 ? "-" : "") + inr(totals.net), color: C.gray900, bg: C.gray50 },
  ];
  const cardW = (PAGE_W - MARGIN * 2 - 16) / 3;
  summaryCards.forEach((c, i) => {
    const x = MARGIN + (cardW + 8) * i;
    setFill(c.bg);
    doc.roundedRect(x, y, cardW, 50, 6, 6, "F");
    setText(C.gray500);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(c.label, x + 12, y + 18);
    setText(c.color);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(c.value, x + 12, y + 38);
  });
  y += 62;
  body("Transfers are excluded from Income and Expense totals (PRD \u00a76.9).", 8, "italic", C.gray500);
  y += 10;

  // ----------- 4. MONTHLY TREND TABLE -----------
  h2("Monthly Trend");
  const byMonth = new Map();
  for (const t of transactions) {
    const d = (() => {
      const m = (t.date || "").match(/(\d{1,2})\s+(\w+)\s+(\d{4})/);
      if (!m) return null;
      return `${m[2]} ${m[3]}`;
    })();
    if (!d) continue;
    if (!byMonth.has(d)) byMonth.set(d, { income: 0, expense: 0 });
    const slot = byMonth.get(d);
    if (t.type === "income") slot.income += Math.abs(t.amountNum || 0);
    else if (t.type === "expense") slot.expense += Math.abs(t.amountNum || 0);
  }
  const monthRows = [...byMonth.entries()];
  if (monthRows.length === 0) monthRows.push(["—", { income: 0, expense: 0 }]);

  // Table header
  const colW = [(PAGE_W - MARGIN * 2) * 0.4, (PAGE_W - MARGIN * 2) * 0.2, (PAGE_W - MARGIN * 2) * 0.2, (PAGE_W - MARGIN * 2) * 0.2];
  setFill(C.gray50);
  doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 22, "F");
  setText(C.gray500);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("MONTH",    MARGIN + 10,                                    y + 14);
  doc.text("INCOME",   MARGIN + colW[0] + colW[1] - 10,                y + 14, { align: "right" });
  doc.text("EXPENSES", MARGIN + colW[0] + colW[1] + colW[2] - 10,      y + 14, { align: "right" });
  doc.text("NET",      MARGIN + colW[0] + colW[1] + colW[2] + colW[3] - 10, y + 14, { align: "right" });
  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  monthRows.forEach(([m, vals], idx) => {
    ensureSpace(20);
    if (idx % 2) { setFill(C.gray50); doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 20, "F"); }
    setText(C.gray900);
    doc.text(m, MARGIN + 10, y + 14);
    setText(C.emerald);
    doc.text(inr(vals.income),  MARGIN + colW[0] + colW[1] - 10,                y + 14, { align: "right" });
    setText(C.rose);
    doc.text(inr(vals.expense), MARGIN + colW[0] + colW[1] + colW[2] - 10,      y + 14, { align: "right" });
    setText(C.gray900);
    doc.text(inr(vals.income - vals.expense), MARGIN + colW[0] + colW[1] + colW[2] + colW[3] - 10, y + 14, { align: "right" });
    y += 20;
  });
  y += 12;

  // ----------- 5. CATEGORY BREAKDOWN -----------
  h2("Expenses by Category");
  const byCat = new Map();
  let catTotal = 0;
  for (const t of transactions) {
    if (t.type !== "expense") continue;
    const key = t.category || "Uncategorized";
    byCat.set(key, (byCat.get(key) || 0) + Math.abs(t.amountNum || 0));
    catTotal += Math.abs(t.amountNum || 0);
  }
  const catSorted = [...byCat.entries()].sort((a,b) => b[1] - a[1]);

  if (catSorted.length === 0) {
    body("No expenses recorded.", 9.5, "italic", C.gray500);
    y += 4;
  } else {
    setFill(C.gray50); doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 22, "F");
    setText(C.gray500); doc.setFont("helvetica", "bold"); doc.setFontSize(8);
    doc.text("CATEGORY", MARGIN + 10, y + 14);
    doc.text("AMOUNT", PAGE_W - MARGIN - 80, y + 14, { align: "right" });
    doc.text("SHARE",  PAGE_W - MARGIN - 10, y + 14, { align: "right" });
    y += 22;
    doc.setFont("helvetica", "normal"); doc.setFontSize(9);
    catSorted.forEach(([name, amt], idx) => {
      ensureSpace(20);
      if (idx % 2) { setFill(C.gray50); doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 20, "F"); }
      setText(C.gray900); doc.text(name, MARGIN + 10, y + 14);
      setText(C.rose); doc.text(inr(amt), PAGE_W - MARGIN - 80, y + 14, { align: "right" });
      setText(C.gray500); doc.text(((amt / catTotal) * 100).toFixed(0) + "%", PAGE_W - MARGIN - 10, y + 14, { align: "right" });
      y += 20;
    });
  }
  y += 12;

  // ----------- 6. PURPOSE BREAKDOWN -----------
  h2("Expenses by Purpose");
  const byPurpose = new Map();
  let purposeTotal = 0;
  for (const t of transactions) {
    if (t.type !== "expense") continue;
    const key = t.purpose || "Personal";
    byPurpose.set(key, (byPurpose.get(key) || 0) + Math.abs(t.amountNum || 0));
    purposeTotal += Math.abs(t.amountNum || 0);
  }
  if (byPurpose.size === 0) {
    body("No expenses recorded.", 9.5, "italic", C.gray500);
    y += 4;
  } else {
    [...byPurpose.entries()].forEach(([p, amt], idx) => {
      ensureSpace(18);
      setText(C.gray900); doc.setFont("helvetica", "normal"); doc.setFontSize(9.5);
      doc.text(p, MARGIN + 10, y + 12);
      setText(C.gray700);
      doc.text(`${inr(amt)}   (${((amt / purposeTotal) * 100).toFixed(0)}%)`, PAGE_W - MARGIN - 10, y + 12, { align: "right" });
      y += 18;
    });
  }
  y += 12;

  // ----------- 7. ACCOUNT-LEVEL BREAKDOWN -----------
  h2("Account-level Breakdown");
  const byAcct = new Map();
  for (const t of transactions) {
    const key = t.account || "—";
    if (!byAcct.has(key)) byAcct.set(key, { in: 0, out: 0, count: 0 });
    const slot = byAcct.get(key);
    if (t.type === "income") slot.in += Math.abs(t.amountNum || 0);
    else if (t.type === "expense") slot.out += Math.abs(t.amountNum || 0);
    slot.count += 1;
  }
  setFill(C.gray50); doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 22, "F");
  setText(C.gray500); doc.setFont("helvetica", "bold"); doc.setFontSize(8);
  doc.text("ACCOUNT",   MARGIN + 10, y + 14);
  doc.text("TXNS",      MARGIN + (PAGE_W - MARGIN * 2) * 0.45, y + 14, { align: "right" });
  doc.text("INFLOW",    MARGIN + (PAGE_W - MARGIN * 2) * 0.7,  y + 14, { align: "right" });
  doc.text("OUTFLOW",   PAGE_W - MARGIN - 10, y + 14, { align: "right" });
  y += 22;
  doc.setFont("helvetica", "normal"); doc.setFontSize(9);
  [...byAcct.entries()].forEach(([name, v], idx) => {
    ensureSpace(20);
    if (idx % 2) { setFill(C.gray50); doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 20, "F"); }
    setText(C.gray900); doc.text(name, MARGIN + 10, y + 14);
    setText(C.gray700); doc.text(String(v.count), MARGIN + (PAGE_W - MARGIN * 2) * 0.45, y + 14, { align: "right" });
    setText(C.emerald); doc.text(inr(v.in),  MARGIN + (PAGE_W - MARGIN * 2) * 0.7, y + 14, { align: "right" });
    setText(C.rose);    doc.text(inr(v.out), PAGE_W - MARGIN - 10, y + 14, { align: "right" });
    y += 20;
  });
  y += 12;

  // ----------- 8. TRANSACTION REGISTER -----------
  doc.addPage();
  y = MARGIN;
  h2("Transaction Register");
  if (transactions.length === 0) {
    body("No transactions recorded.", 9.5, "italic", C.gray500);
  } else {
    const sorted = [...transactions].sort((a, b) => {
      const da = (a.date || "").match(/(\d{1,2})\s+(\w+)\s+(\d{4})/);
      const db = (b.date || "").match(/(\d{1,2})\s+(\w+)\s+(\d{4})/);
      if (!da || !db) return 0;
      const ma = MONTH_NAMES.findIndex(n => n.toLowerCase().startsWith(da[2].toLowerCase()));
      const mb = MONTH_NAMES.findIndex(n => n.toLowerCase().startsWith(db[2].toLowerCase()));
      return new Date(da[3], ma, da[1]) - new Date(db[3], mb, db[1]);
    });
    const cols = [0.16, 0.26, 0.20, 0.18, 0.10, 0.10]; // date, merchant, category, account, mode, amount
    const headers = ["DATE", "MERCHANT", "CATEGORY", "ACCOUNT", "MODE", "AMOUNT"];
    const width = PAGE_W - MARGIN * 2;
    const colX = [0];
    for (let i = 0; i < cols.length; i++) colX.push(colX[i] + cols[i] * width);

    setFill(C.gray50); doc.rect(MARGIN, y, width, 22, "F");
    setText(C.gray500); doc.setFont("helvetica", "bold"); doc.setFontSize(8);
    headers.forEach((h, i) => {
      doc.text(h, MARGIN + colX[i] + (i === headers.length - 1 ? cols[i] * width - 10 : 6), y + 14,
        i === headers.length - 1 ? { align: "right" } : {});
    });
    y += 22;

    doc.setFont("helvetica", "normal"); doc.setFontSize(8.5);
    sorted.forEach((t, idx) => {
      ensureSpace(18);
      if (idx % 2) { setFill(C.gray50); doc.rect(MARGIN, y, width, 18, "F"); }
      setText(C.gray900);
      const trunc = (s, n) => { s = String(s || "—"); return s.length > n ? s.slice(0, n-1) + "…" : s; };
      doc.text(trunc(t.date, 14), MARGIN + colX[0] + 6, y + 12);
      doc.text(trunc(t.label, 22), MARGIN + colX[1] + 6, y + 12);
      doc.text(trunc(t.category, 18), MARGIN + colX[2] + 6, y + 12);
      doc.text(trunc(t.account, 16), MARGIN + colX[3] + 6, y + 12);
      doc.text(trunc(t.mode, 10), MARGIN + colX[4] + 6, y + 12);
      const fg = t.type === "income" ? C.emerald : t.type === "expense" ? C.rose : C.gray700;
      const sign = t.type === "income" ? "+" : t.type === "expense" ? "-" : "";
      setText(fg);
      doc.text(sign + inr(t.amountNum || 0), MARGIN + colX[5] + cols[5] * width - 10, y + 12, { align: "right" });
      y += 18;
    });
  }
  y += 16;

  // ----------- 9. ANOMALIES -----------
  h2("Anomalies & Quality Flags");
  const uncategorized = transactions.filter(t => t.type === "expense" && !t.category).length;
  const large = transactions.filter(t => (t.amountNum || 0) >= 1000000).length;
  const dupKept = transactions.filter(t => t.source === "Add Anyway").length;
  if (uncategorized + large + dupKept === 0) {
    body("No flags. Records look clean.", 9.5, "normal", C.gray700);
  } else {
    if (uncategorized) body(`• ${uncategorized} uncategorized expense${uncategorized > 1 ? "s" : ""}`);
    if (large)        body(`• ${large} transaction${large > 1 ? "s" : ""} \u2265 Rs.10 lakh — verify before filing`);
    if (dupKept)      body(`• ${dupKept} transaction${dupKept > 1 ? "s" : ""} kept after duplicate prompt`);
  }

  // Footer on last page
  addFooter();
  // Footer on all earlier pages (jsPDF doesn't auto-do this, addFooter was called via ensureSpace)
  const total = doc.internal.getNumberOfPages();
  for (let p = 1; p < total; p++) {
    doc.setPage(p);
    setText(C.gray400); doc.setFontSize(8); doc.setFont("helvetica", "normal");
    const txt = "Generated by WiseTransact based on user-entered data. Verify all entries with original bank statements and consult a qualified Chartered Accountant before tax filing.";
    const lines = doc.splitTextToSize(txt, PAGE_W - MARGIN * 2);
    doc.text(lines, MARGIN, PAGE_H - 30);
    doc.text(`Page ${p}`, PAGE_W - MARGIN, PAGE_H - 30, { align: "right" });
  }
  doc.setPage(total);

  // Save
  const safePeriod = periodLabel.replace(/\s+/g, "_");
  doc.save(`WiseTransact_${safePeriod}.pdf`);
};

window.generateReportPdf = generateReportPdf;
